-- ========================================================
-- FLOW DATABASE INITIALIZATION (POLICY-ENFORCED)
-- PostgreSQL 18+
-- Combined file for docker-entrypoint-initdb.d
-- ========================================================

BEGIN;

-- 0. Roles
-- --------------------------------------------------------
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'db_owner') THEN
        CREATE ROLE db_owner NOLOGIN;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'db_service') THEN
        CREATE ROLE db_service NOLOGIN;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'app_user') THEN
        CREATE ROLE app_user LOGIN PASSWORD 'app_pass';
    ELSE
        ALTER ROLE app_user WITH PASSWORD 'app_pass';
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'db_admin') THEN
        CREATE ROLE db_admin NOLOGIN;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'db_batch') THEN
        CREATE ROLE db_batch NOLOGIN;
    END IF;
END $$;

-- --------------------------------------------------------

-- 1. Schemas
-- --------------------------------------------------------
DROP SCHEMA IF EXISTS core CASCADE;
DROP SCHEMA IF EXISTS ref CASCADE;
DROP SCHEMA IF EXISTS workflow CASCADE;
DROP SCHEMA IF EXISTS audit CASCADE;

CREATE SCHEMA core AUTHORIZATION db_owner;
CREATE SCHEMA ref AUTHORIZATION db_owner;
CREATE SCHEMA workflow AUTHORIZATION db_owner;
CREATE SCHEMA audit AUTHORIZATION db_owner;

-- --------------------------------------------------------

-- 2. Reference / Lookup Tables (schema: ref)
-- --------------------------------------------------------
SET search_path = ref;

CREATE TABLE areas (
    area_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    area_name VARCHAR(45) NOT NULL UNIQUE,
    area_acronym VARCHAR(5) NOT NULL UNIQUE
);

CREATE TABLE disciplines (
    discipline_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    discipline_name VARCHAR(45) NOT NULL UNIQUE,
    discipline_acronym VARCHAR(5) NOT NULL UNIQUE
);

CREATE TABLE projects (
    project_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_name VARCHAR(45) NOT NULL UNIQUE
);

CREATE TABLE units (
    unit_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    unit_name VARCHAR(45) NOT NULL UNIQUE
);

CREATE TABLE jobpacks (
    jobpack_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    jobpack_name VARCHAR(45) NOT NULL UNIQUE
);

CREATE TABLE roles (
    role_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name VARCHAR(45) NOT NULL UNIQUE
);

CREATE TABLE doc_rev_milestones (
    milestone_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    milestone_name VARCHAR(45) NOT NULL UNIQUE,
    progress SMALLINT DEFAULT 0
);

CREATE TABLE revision_overview (
    rev_code_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rev_code_name VARCHAR(15) NOT NULL UNIQUE,
    rev_code_acronym VARCHAR(5) NOT NULL,
    rev_description VARCHAR(45) NOT NULL UNIQUE,
    percentage SMALLINT
);

CREATE TABLE doc_rev_status_ui_behaviors (
    ui_behavior_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ui_behavior_name VARCHAR(64) NOT NULL UNIQUE,
    ui_behavior_file VARCHAR(64) NOT NULL UNIQUE
);

CREATE TABLE doc_rev_statuses (
    rev_status_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rev_status_name VARCHAR(45) NOT NULL UNIQUE,
    ui_behavior_id SMALLINT NOT NULL REFERENCES ref.doc_rev_status_ui_behaviors(ui_behavior_id),
    next_rev_status_id SMALLINT REFERENCES ref.doc_rev_statuses(rev_status_id),
    revertible BOOLEAN NOT NULL DEFAULT TRUE,
    editable BOOLEAN NOT NULL DEFAULT TRUE,
    final BOOLEAN NOT NULL DEFAULT FALSE,
    start BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT chk_doc_rev_statuses_no_self_ref CHECK (
        next_rev_status_id IS NULL OR next_rev_status_id <> rev_status_id
    ),
    CONSTRAINT chk_doc_rev_statuses_final_flags CHECK (
        NOT final OR (editable = FALSE AND revertible = FALSE)
    ),
    CONSTRAINT chk_doc_rev_statuses_final_next_eq CHECK (
        final = (next_rev_status_id IS NULL)
    )
);

CREATE UNIQUE INDEX ux_doc_rev_statuses_single_final
    ON ref.doc_rev_statuses ((next_rev_status_id IS NULL))
    WHERE next_rev_status_id IS NULL;

CREATE UNIQUE INDEX ux_doc_rev_statuses_single_start
    ON ref.doc_rev_statuses (start)
    WHERE start = TRUE;

CREATE OR REPLACE FUNCTION ref.doc_rev_statuses_prevent_cycle()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ref, pg_temp
AS $$
DECLARE
    current_id SMALLINT;
BEGIN
    IF NEW.next_rev_status_id IS NULL THEN
        RETURN NEW;
    END IF;

    current_id := NEW.next_rev_status_id;
    WHILE current_id IS NOT NULL LOOP
        IF NEW.rev_status_id IS NOT NULL AND current_id = NEW.rev_status_id THEN
            RAISE EXCEPTION 'Cycle detected in doc_rev_statuses';
        END IF;

        SELECT next_rev_status_id
        INTO current_id
        FROM ref.doc_rev_statuses
        WHERE rev_status_id = current_id;
    END LOOP;

    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_doc_rev_statuses_prevent_cycle
BEFORE INSERT OR UPDATE OF next_rev_status_id
ON ref.doc_rev_statuses
FOR EACH ROW
EXECUTE FUNCTION ref.doc_rev_statuses_prevent_cycle();

CREATE TABLE files_accepted (
    file_type VARCHAR(10) PRIMARY KEY,
    mimetype VARCHAR(90) NOT NULL
);

CREATE TABLE leased_doc_nums (
    doc_number VARCHAR(45) NOT NULL,
    created_date TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE sql_queries (
    id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    query VARCHAR(4096) NOT NULL,
    titles VARCHAR(1024),
    project_filtered_field VARCHAR(45),
    discipline_filtered_field VARCHAR(45)
);

CREATE TABLE person (
    person_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_name VARCHAR(45) NOT NULL,
    photo_s3_uid TEXT,
    email VARCHAR(255)
);

CREATE TABLE users (
    user_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id SMALLINT NOT NULL REFERENCES ref.person(person_id),
    user_acronym VARCHAR(10) NOT NULL,
    role_id SMALLINT NOT NULL REFERENCES ref.roles(role_id),
    UNIQUE (person_id)
);

CREATE TABLE doc_types (
    type_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_type_name VARCHAR(45) NOT NULL,
    ref_discipline_id SMALLINT NOT NULL REFERENCES ref.disciplines(discipline_id),
    doc_type_acronym VARCHAR(10) NOT NULL
);

CREATE TABLE distribution_list (
    dist_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    distribution_list_name VARCHAR(45) NOT NULL,
    project_id SMALLINT NOT NULL REFERENCES ref.projects(project_id)
);

CREATE TABLE distribution_list_content (
    dist_id SMALLINT NOT NULL REFERENCES ref.distribution_list(dist_id),
    person_id SMALLINT NOT NULL REFERENCES ref.person(person_id),
    PRIMARY KEY (dist_id, person_id)
);

CREATE TABLE permissions (
    permission_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id SMALLINT NOT NULL REFERENCES ref.users(user_id),
    project_id SMALLINT REFERENCES ref.projects(project_id),
    discipline_id SMALLINT REFERENCES ref.disciplines(discipline_id),
    CONSTRAINT chk_permissions_scope CHECK (project_id IS NOT NULL OR discipline_id IS NOT NULL)
);

CREATE UNIQUE INDEX uq_permissions_user_proj_disc
    ON ref.permissions(user_id, project_id, discipline_id)
    WHERE project_id IS NOT NULL AND discipline_id IS NOT NULL;

CREATE UNIQUE INDEX uq_permissions_user_proj_anydisc
    ON ref.permissions(user_id, project_id)
    WHERE discipline_id IS NULL;

CREATE UNIQUE INDEX uq_permissions_user_anyproj_disc
    ON ref.permissions(user_id, discipline_id)
    WHERE project_id IS NULL;

CREATE UNIQUE INDEX uq_permissions_user_anyscope
    ON ref.permissions(user_id)
    WHERE project_id IS NULL AND discipline_id IS NULL;

CREATE TABLE doc_cache (
    user_id SMALLINT NOT NULL,
    project_id SMALLINT NOT NULL REFERENCES ref.projects(project_id),
    doc_name_unique VARCHAR(45) NOT NULL UNIQUE,
    title VARCHAR(45) NOT NULL,
    jobpack_id SMALLINT REFERENCES ref.jobpacks(jobpack_id),
    type_id SMALLINT NOT NULL REFERENCES ref.doc_types(type_id),
    area_id SMALLINT NOT NULL REFERENCES ref.areas(area_id),
    unit_id SMALLINT NOT NULL REFERENCES ref.units(unit_id),
    PRIMARY KEY (user_id, project_id, doc_name_unique)
);

-- --------------------------------------------------------

-- 3. Core Tables (schema: core)
-- --------------------------------------------------------
SET search_path = core;

CREATE TABLE doc (
    doc_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_name_unique VARCHAR(45) NOT NULL UNIQUE,
    title VARCHAR(45) NOT NULL,
    project_id SMALLINT REFERENCES ref.projects(project_id),
    jobpack_id SMALLINT REFERENCES ref.jobpacks(jobpack_id),
    type_id SMALLINT NOT NULL REFERENCES ref.doc_types(type_id),
    area_id SMALLINT NOT NULL REFERENCES ref.areas(area_id),
    unit_id SMALLINT NOT NULL REFERENCES ref.units(unit_id),
    rev_actual_id INTEGER,
    rev_current_id INTEGER,
    voided BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by SMALLINT REFERENCES ref.users(user_id),
    updated_by SMALLINT REFERENCES ref.users(user_id)
);

CREATE TABLE doc_revision (
    rev_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_id INTEGER NOT NULL REFERENCES core.doc(doc_id) ON DELETE CASCADE,
    rev_code_id SMALLINT NOT NULL REFERENCES ref.revision_overview(rev_code_id),
    seq_num SMALLINT NOT NULL DEFAULT 1,
    rev_status_id SMALLINT NOT NULL REFERENCES ref.doc_rev_statuses(rev_status_id),
    superseded BOOLEAN NOT NULL DEFAULT FALSE,
    transmital_current_revision VARCHAR(45) NOT NULL,
    milestone_id SMALLINT REFERENCES ref.doc_rev_milestones(milestone_id),
    planned_start_date TIMESTAMPTZ NOT NULL,
    planned_finish_date TIMESTAMPTZ NOT NULL,
    actual_start_date TIMESTAMPTZ,
    actual_finish_date TIMESTAMPTZ,
    canceled_date TIMESTAMPTZ,
    rev_author_id SMALLINT NOT NULL REFERENCES ref.person(person_id),
    rev_originator_id SMALLINT NOT NULL REFERENCES ref.person(person_id),
    rev_modifier_id SMALLINT NOT NULL REFERENCES ref.person(person_id),
    modified_doc_date TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    as_built BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by SMALLINT REFERENCES ref.users(user_id),
    updated_by SMALLINT REFERENCES ref.users(user_id)
);

CREATE UNIQUE INDEX ux_doc_revision_rev_doc
    ON core.doc_revision (rev_id, doc_id);

ALTER TABLE core.doc
    ADD CONSTRAINT fk_doc_rev_current
        FOREIGN KEY (rev_current_id, doc_id)
        REFERENCES core.doc_revision (rev_id, doc_id)
        DEFERRABLE INITIALLY DEFERRED,
    ADD CONSTRAINT fk_doc_rev_actual
        FOREIGN KEY (rev_actual_id, doc_id)
        REFERENCES core.doc_revision (rev_id, doc_id)
        DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE files (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rev_id INTEGER NOT NULL REFERENCES core.doc_revision(rev_id) ON DELETE CASCADE,
    filename VARCHAR(90) NOT NULL,
    s3_uid TEXT NOT NULL,
    mimetype VARCHAR(90) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by SMALLINT REFERENCES ref.users(user_id),
    updated_by SMALLINT REFERENCES ref.users(user_id)
);

CREATE TABLE files_commented (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_id INTEGER NOT NULL REFERENCES core.files(id) ON DELETE CASCADE,
    user_id SMALLINT NOT NULL REFERENCES ref.users(user_id),
    s3_uid TEXT NOT NULL,
    mimetype VARCHAR(90) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by SMALLINT REFERENCES ref.users(user_id),
    updated_by SMALLINT REFERENCES ref.users(user_id),
    UNIQUE(file_id, user_id)
);

CREATE INDEX idx_files_commented_file_id ON core.files_commented (file_id);

-- --------------------------------------------------------

-- 4. Audit Tables (schema: audit)
-- --------------------------------------------------------
SET search_path = audit;

CREATE TABLE revision_status_audit (
    audit_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rev_id INTEGER NOT NULL,
    doc_id INTEGER NOT NULL,
    from_status_id SMALLINT,
    to_status_id SMALLINT NOT NULL,
    action VARCHAR(64) NOT NULL,
    reason TEXT,
    changed_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    changed_by SMALLINT
);

CREATE TABLE admin_override_audit (
    audit_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rev_id INTEGER NOT NULL,
    doc_id INTEGER NOT NULL,
    from_status_id SMALLINT,
    to_status_id SMALLINT NOT NULL,
    reason TEXT NOT NULL,
    changed_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    changed_by SMALLINT
);

CREATE TABLE doc_revision_history (
    rev_id INTEGER NOT NULL,
    rev_code_id SMALLINT NOT NULL,
    rev_date TIMESTAMPTZ NOT NULL,
    rev_author_id SMALLINT NOT NULL,
    rev_originator_id SMALLINT NOT NULL,
    as_built BOOLEAN NOT NULL DEFAULT FALSE,
    superseded BOOLEAN NOT NULL DEFAULT FALSE,
    transmital_current_revision VARCHAR(45) NOT NULL,
    milestone_id SMALLINT,
    planned_start_date TIMESTAMPTZ NOT NULL,
    planned_finish_date TIMESTAMPTZ NOT NULL,
    actual_start_date TIMESTAMPTZ,
    actual_finish_date TIMESTAMPTZ,
    canceled_date TIMESTAMPTZ,
    rev_status_id SMALLINT NOT NULL,
    doc_id INTEGER NOT NULL,
    seq_num SMALLINT NOT NULL,
    archived_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (rev_id, archived_at)
);

-- --------------------------------------------------------

-- 5. Utility Triggers (timestamps, created_by)
-- --------------------------------------------------------
SET search_path = core, ref;

CREATE OR REPLACE FUNCTION core.fn_update_timestamp() RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = core, ref, pg_temp
AS $$
BEGIN
    IF NEW.updated_at IS NULL THEN
        NEW.updated_at = CURRENT_TIMESTAMP;
    END IF;
    IF NEW.updated_by IS NULL THEN
        NEW.updated_by = NULLIF(current_setting('app.user', true), '')::SMALLINT;
    END IF;
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION core.fn_set_created_by() RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = core, ref, pg_temp
AS $$
BEGIN
    IF NEW.created_by IS NULL THEN
        NEW.created_by = NULLIF(current_setting('app.user', true), '')::SMALLINT;
    END IF;
    IF NEW.updated_by IS NULL THEN
        NEW.updated_by = NULLIF(current_setting('app.user', true), '')::SMALLINT;
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER tr_doc_update_timestamp
BEFORE UPDATE ON core.doc
FOR EACH ROW EXECUTE FUNCTION core.fn_update_timestamp();

CREATE TRIGGER tr_doc_set_created_by
BEFORE INSERT ON core.doc
FOR EACH ROW EXECUTE FUNCTION core.fn_set_created_by();

CREATE TRIGGER tr_doc_revision_update_timestamp
BEFORE UPDATE ON core.doc_revision
FOR EACH ROW EXECUTE FUNCTION core.fn_update_timestamp();

CREATE TRIGGER tr_doc_revision_set_created_by
BEFORE INSERT ON core.doc_revision
FOR EACH ROW EXECUTE FUNCTION core.fn_set_created_by();

CREATE TRIGGER tr_files_update_timestamp
BEFORE UPDATE ON core.files
FOR EACH ROW EXECUTE FUNCTION core.fn_update_timestamp();

CREATE TRIGGER tr_files_set_created_by
BEFORE INSERT ON core.files
FOR EACH ROW EXECUTE FUNCTION core.fn_set_created_by();

CREATE TRIGGER tr_files_commented_update_timestamp
BEFORE UPDATE ON core.files_commented
FOR EACH ROW EXECUTE FUNCTION core.fn_update_timestamp();

CREATE TRIGGER tr_files_commented_set_created_by
BEFORE INSERT ON core.files_commented
FOR EACH ROW EXECUTE FUNCTION core.fn_set_created_by();

CREATE OR REPLACE FUNCTION core.fn_files_commented_check_mimetype() RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = core, ref, pg_temp
AS $$
DECLARE
    original_mimetype VARCHAR(90);
BEGIN
    SELECT mimetype INTO original_mimetype FROM core.files WHERE id = NEW.file_id;
    IF original_mimetype IS NULL THEN
        RAISE EXCEPTION 'File not found for commented file_id=%', NEW.file_id
            USING ERRCODE = '23503';
    END IF;
    IF NEW.mimetype IS NULL OR lower(NEW.mimetype) <> lower(original_mimetype) THEN
        RAISE EXCEPTION 'Commented file mimetype % does not match original %',
            NEW.mimetype, original_mimetype
            USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER tr_files_commented_check_mimetype
BEFORE INSERT OR UPDATE ON core.files_commented
FOR EACH ROW EXECUTE FUNCTION core.fn_files_commented_check_mimetype();

-- --------------------------------------------------------

-- 6. Policy Enforcement Triggers
-- --------------------------------------------------------
CREATE OR REPLACE FUNCTION core.fn_doc_revision_enforce_rules() RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = core, ref, pg_temp
AS $$
DECLARE
    v_new_status ref.doc_rev_statuses%ROWTYPE;
    v_old_status ref.doc_rev_statuses%ROWTYPE;
    v_has_other BOOLEAN;
BEGIN
    -- lock document row to serialize per-doc transitions
    PERFORM 1 FROM core.doc WHERE doc_id = NEW.doc_id FOR UPDATE;

    SELECT * INTO v_new_status FROM ref.doc_rev_statuses WHERE rev_status_id = NEW.rev_status_id;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'Invalid revision status';
    END IF;

    IF TG_OP = 'UPDATE' THEN
        SELECT * INTO v_old_status FROM ref.doc_rev_statuses WHERE rev_status_id = OLD.rev_status_id;
        -- Final revisions are immutable unless explicitly overridden
        IF v_old_status.final THEN
            IF COALESCE(current_setting('app.action', true), '') NOT IN (
                'transition_final', 'supersede_final', 'admin_override'
            ) THEN
                RAISE EXCEPTION 'Final revision is immutable';
            END IF;
        END IF;
        -- Superseded revisions cannot transition
        IF OLD.superseded AND NEW.rev_status_id <> OLD.rev_status_id THEN
            RAISE EXCEPTION 'Superseded revision cannot be transitioned';
        END IF;
    END IF;

    -- Rule 3: Only one active (non-final, non-canceled) revision per document
    IF NEW.canceled_date IS NULL AND NOT v_new_status.final THEN
        SELECT EXISTS (
            SELECT 1
            FROM core.doc_revision r
            JOIN ref.doc_rev_statuses s ON s.rev_status_id = r.rev_status_id
            WHERE r.doc_id = NEW.doc_id
              AND r.rev_id <> COALESCE(NEW.rev_id, 0)
              AND r.canceled_date IS NULL
              AND NOT s.final
        ) INTO v_has_other;
        IF v_has_other THEN
            RAISE EXCEPTION 'Only one active (non-final, non-canceled) revision allowed per document';
        END IF;
    END IF;

    -- Rule 4: Only one final and not superseded per document
    IF v_new_status.final AND COALESCE(NEW.superseded, false) = false THEN
        SELECT EXISTS (
            SELECT 1
            FROM core.doc_revision r
            JOIN ref.doc_rev_statuses s ON s.rev_status_id = r.rev_status_id
            WHERE r.doc_id = NEW.doc_id
              AND r.rev_id <> COALESCE(NEW.rev_id, 0)
              AND s.final
              AND COALESCE(r.superseded, false) = false
        ) INTO v_has_other;
        IF v_has_other THEN
            RAISE EXCEPTION 'Only one final (not superseded) revision allowed per document';
        END IF;
    END IF;

    RETURN NEW;
END;
$$;

CREATE TRIGGER tr_doc_revision_enforce_rules
BEFORE INSERT OR UPDATE ON core.doc_revision
FOR EACH ROW EXECUTE FUNCTION core.fn_doc_revision_enforce_rules();

CREATE OR REPLACE FUNCTION core.fn_doc_revision_prevent_delete() RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = core, ref, pg_temp
AS $$
BEGIN
    IF COALESCE(current_setting('app.action', true), '') = 'delete_document' THEN
        RETURN OLD;
    END IF;
    RAISE EXCEPTION 'Revision deletion is forbidden; use cancellation instead';
END;
$$;

CREATE TRIGGER tr_doc_revision_prevent_delete
BEFORE DELETE ON core.doc_revision
FOR EACH ROW EXECUTE FUNCTION core.fn_doc_revision_prevent_delete();

CREATE OR REPLACE FUNCTION core.fn_doc_prevent_delete_if_final() RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = core, ref, pg_temp
AS $$
DECLARE
    v_has_final BOOLEAN;
BEGIN
    SELECT EXISTS (
        SELECT 1
        FROM core.doc_revision r
        JOIN ref.doc_rev_statuses s ON s.rev_status_id = r.rev_status_id
        WHERE r.doc_id = OLD.doc_id
          AND s.final
    ) INTO v_has_final;

    IF v_has_final THEN
        RAISE EXCEPTION 'Document deletion forbidden: final revision exists';
    END IF;

    RETURN OLD;
END;
$$;

CREATE TRIGGER tr_doc_prevent_delete_if_final
BEFORE DELETE ON core.doc
FOR EACH ROW EXECUTE FUNCTION core.fn_doc_prevent_delete_if_final();

-- --------------------------------------------------------

-- 7. Workflow Functions (schema: workflow)
-- --------------------------------------------------------
SET search_path = workflow;

CREATE OR REPLACE FUNCTION workflow.create_document(
    p_doc_name_unique VARCHAR,
    p_title VARCHAR,
    p_project_id SMALLINT,
    p_jobpack_id SMALLINT,
    p_type_id SMALLINT,
    p_area_id SMALLINT,
    p_unit_id SMALLINT,
    p_rev_code_id SMALLINT,
    p_rev_author_id SMALLINT,
    p_rev_originator_id SMALLINT,
    p_rev_modifier_id SMALLINT,
    p_transmital_current_revision VARCHAR,
    p_milestone_id SMALLINT,
    p_planned_start_date TIMESTAMPTZ,
    p_planned_finish_date TIMESTAMPTZ,
    p_actual_start_date TIMESTAMPTZ,
    p_actual_finish_date TIMESTAMPTZ,
    p_modified_doc_date TIMESTAMPTZ,
    p_as_built BOOLEAN DEFAULT FALSE
) RETURNS TABLE (doc_id INTEGER, rev_id INTEGER)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = core, ref, workflow, audit, pg_temp
AS $$
DECLARE
    v_start_status SMALLINT;
    v_doc_id INTEGER;
BEGIN
    SELECT rev_status_id INTO v_start_status
    FROM ref.doc_rev_statuses WHERE start = TRUE LIMIT 1;

    IF v_start_status IS NULL THEN
        RAISE EXCEPTION 'No start status configured';
    END IF;

    INSERT INTO core.doc (
        doc_name_unique, title, project_id, jobpack_id, type_id, area_id, unit_id
    ) VALUES (
        p_doc_name_unique, p_title, p_project_id, p_jobpack_id, p_type_id, p_area_id, p_unit_id
    ) RETURNING core.doc.doc_id INTO v_doc_id;

    INSERT INTO core.doc_revision (
        doc_id,
        rev_code_id,
        rev_author_id,
        rev_originator_id,
        rev_modifier_id,
        transmital_current_revision,
        milestone_id,
        planned_start_date,
        planned_finish_date,
        actual_start_date,
        actual_finish_date,
        canceled_date,
        rev_status_id,
        seq_num,
        modified_doc_date,
        as_built
    ) VALUES (
        v_doc_id,
        p_rev_code_id,
        p_rev_author_id,
        p_rev_originator_id,
        p_rev_modifier_id,
        p_transmital_current_revision,
        p_milestone_id,
        p_planned_start_date,
        p_planned_finish_date,
        p_actual_start_date,
        p_actual_finish_date,
        NULL,
        v_start_status,
        1,
        COALESCE(p_modified_doc_date, CURRENT_TIMESTAMP),
        COALESCE(p_as_built, FALSE)
    ) RETURNING core.doc_revision.rev_id INTO rev_id;

    UPDATE core.doc
    SET rev_current_id = rev_id
    WHERE core.doc.doc_id = v_doc_id;

    RETURN QUERY SELECT v_doc_id, rev_id;
END;
$$;

CREATE OR REPLACE FUNCTION workflow.create_revision(
    p_doc_id INTEGER,
    p_rev_code_id SMALLINT,
    p_rev_author_id SMALLINT,
    p_rev_originator_id SMALLINT,
    p_rev_modifier_id SMALLINT,
    p_transmital_current_revision VARCHAR,
    p_milestone_id SMALLINT,
    p_planned_start_date TIMESTAMPTZ,
    p_planned_finish_date TIMESTAMPTZ,
    p_actual_start_date TIMESTAMPTZ,
    p_actual_finish_date TIMESTAMPTZ,
    p_modified_doc_date TIMESTAMPTZ,
    p_as_built BOOLEAN DEFAULT FALSE
) RETURNS INTEGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = core, ref, workflow, audit, pg_temp
AS $$
DECLARE
    v_start_status SMALLINT;
    v_seq SMALLINT;
    v_rev_id INTEGER;
BEGIN
    SELECT rev_status_id INTO v_start_status
    FROM ref.doc_rev_statuses WHERE start = TRUE LIMIT 1;

    IF v_start_status IS NULL THEN
        RAISE EXCEPTION 'No start status configured';
    END IF;

    SELECT COALESCE(MAX(seq_num), 0) + 1 INTO v_seq
    FROM core.doc_revision WHERE doc_id = p_doc_id;

    INSERT INTO core.doc_revision (
        doc_id,
        rev_code_id,
        rev_author_id,
        rev_originator_id,
        rev_modifier_id,
        transmital_current_revision,
        milestone_id,
        planned_start_date,
        planned_finish_date,
        actual_start_date,
        actual_finish_date,
        canceled_date,
        rev_status_id,
        seq_num,
        modified_doc_date,
        as_built
    ) VALUES (
        p_doc_id,
        p_rev_code_id,
        p_rev_author_id,
        p_rev_originator_id,
        p_rev_modifier_id,
        p_transmital_current_revision,
        p_milestone_id,
        p_planned_start_date,
        p_planned_finish_date,
        p_actual_start_date,
        p_actual_finish_date,
        NULL,
        v_start_status,
        v_seq,
        COALESCE(p_modified_doc_date, CURRENT_TIMESTAMP),
        COALESCE(p_as_built, FALSE)
    ) RETURNING rev_id INTO v_rev_id;

    UPDATE core.doc
    SET rev_current_id = v_rev_id
    WHERE doc_id = p_doc_id;

    RETURN v_rev_id;
END;
$$;

CREATE OR REPLACE FUNCTION workflow.transition_revision(
    p_rev_id INTEGER,
    p_direction TEXT
) RETURNS core.doc_revision
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = core, ref, workflow, audit, pg_temp
AS $$
DECLARE
    v_rev core.doc_revision%ROWTYPE;
    v_status ref.doc_rev_statuses%ROWTYPE;
    v_next_status ref.doc_rev_statuses%ROWTYPE;
    v_next_status_id SMALLINT;
BEGIN
    SELECT * INTO v_rev FROM core.doc_revision WHERE rev_id = p_rev_id FOR UPDATE;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'Revision not found';
    END IF;

    IF v_rev.superseded THEN
        RAISE EXCEPTION 'Superseded revision cannot be transitioned';
    END IF;

    SELECT * INTO v_status FROM ref.doc_rev_statuses WHERE rev_status_id = v_rev.rev_status_id;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'Invalid current status';
    END IF;

    IF p_direction NOT IN ('forward', 'back') THEN
        RAISE EXCEPTION 'Invalid direction';
    END IF;

    IF p_direction = 'forward' THEN
        IF v_status.final OR v_status.next_rev_status_id IS NULL THEN
            RAISE EXCEPTION 'Revision already at final status';
        END IF;
        v_next_status_id := v_status.next_rev_status_id;
    ELSE
        IF v_status.start THEN
            RAISE EXCEPTION 'Revision already at start status';
        END IF;
        IF NOT v_status.revertible THEN
            RAISE EXCEPTION 'Revision status not revertible';
        END IF;
        SELECT rev_status_id INTO v_next_status_id
        FROM ref.doc_rev_statuses
        WHERE next_rev_status_id = v_status.rev_status_id;
        IF v_next_status_id IS NULL THEN
            RAISE EXCEPTION 'Previous status not found';
        END IF;
    END IF;

    SELECT * INTO v_next_status FROM ref.doc_rev_statuses WHERE rev_status_id = v_next_status_id;

    -- Rule 7: files must exist before entering any non-start state
    IF NOT v_next_status.start THEN
        PERFORM 1 FROM core.files WHERE rev_id = p_rev_id LIMIT 1;
        IF NOT FOUND THEN
            RAISE EXCEPTION 'Files must exist before leaving the start status';
        END IF;
    END IF;

    PERFORM set_config('app.action', 'transition', true);
    UPDATE core.doc_revision
    SET rev_status_id = v_next_status_id
    WHERE rev_id = p_rev_id;

    INSERT INTO audit.revision_status_audit (
        rev_id, doc_id, from_status_id, to_status_id, action, reason, changed_by
    ) VALUES (
        p_rev_id, v_rev.doc_id, v_status.rev_status_id, v_next_status_id, 'transition', NULL,
        NULLIF(current_setting('app.user', true), '')::SMALLINT
    );

    IF v_next_status.final THEN
        PERFORM set_config('app.action', 'transition_final', true);
        -- Supersede previous final revision (if any)
        UPDATE core.doc_revision
        SET superseded = TRUE
        WHERE doc_id = v_rev.doc_id
          AND rev_id <> p_rev_id
          AND rev_status_id IN (SELECT rev_status_id FROM ref.doc_rev_statuses WHERE final = TRUE)
          AND superseded = FALSE;

        UPDATE core.doc
        SET rev_actual_id = p_rev_id,
            rev_current_id = p_rev_id
        WHERE doc_id = v_rev.doc_id;
    END IF;

    SELECT * INTO v_rev FROM core.doc_revision WHERE rev_id = p_rev_id;
    RETURN v_rev;
END;
$$;

CREATE OR REPLACE FUNCTION workflow.cancel_revision(
    p_rev_id INTEGER
) RETURNS core.doc_revision
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = core, ref, workflow, audit, pg_temp
AS $$
DECLARE
    v_rev core.doc_revision%ROWTYPE;
    v_status ref.doc_rev_statuses%ROWTYPE;
BEGIN
    SELECT * INTO v_rev FROM core.doc_revision WHERE rev_id = p_rev_id FOR UPDATE;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'Revision not found';
    END IF;

    SELECT * INTO v_status FROM ref.doc_rev_statuses WHERE rev_status_id = v_rev.rev_status_id;
    IF v_status.final THEN
        RAISE EXCEPTION 'Final revision cannot be canceled';
    END IF;

    IF v_rev.canceled_date IS NULL THEN
        UPDATE core.doc_revision
        SET canceled_date = CURRENT_TIMESTAMP
        WHERE rev_id = p_rev_id;
    END IF;

    UPDATE core.doc
    SET rev_current_id = rev_actual_id
    WHERE doc_id = v_rev.doc_id;

    INSERT INTO audit.revision_status_audit (
        rev_id, doc_id, from_status_id, to_status_id, action, reason, changed_by
    ) VALUES (
        p_rev_id, v_rev.doc_id, v_rev.rev_status_id, v_rev.rev_status_id, 'cancel', NULL,
        NULLIF(current_setting('app.user', true), '')::SMALLINT
    );

    SELECT * INTO v_rev FROM core.doc_revision WHERE rev_id = p_rev_id;
    RETURN v_rev;
END;
$$;

CREATE OR REPLACE FUNCTION workflow.admin_override_transition(
    p_rev_id INTEGER,
    p_target_status_id SMALLINT,
    p_reason TEXT
) RETURNS core.doc_revision
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = core, ref, workflow, audit, pg_temp
AS $$
DECLARE
    v_rev core.doc_revision%ROWTYPE;
    v_from_status SMALLINT;
    v_target ref.doc_rev_statuses%ROWTYPE;
BEGIN
    IF NOT (pg_has_role(current_user, 'db_admin', 'member') OR pg_has_role(current_user, 'db_owner', 'member')) THEN
        RAISE EXCEPTION 'Admin role required';
    END IF;

    SELECT * INTO v_rev FROM core.doc_revision WHERE rev_id = p_rev_id FOR UPDATE;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'Revision not found';
    END IF;

    SELECT * INTO v_target FROM ref.doc_rev_statuses WHERE rev_status_id = p_target_status_id;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'Target status not found';
    END IF;

    -- Rule 7 enforced for non-start target
    IF NOT v_target.start THEN
        PERFORM 1 FROM core.files WHERE rev_id = p_rev_id LIMIT 1;
        IF NOT FOUND THEN
            RAISE EXCEPTION 'Files must exist before leaving the start status';
        END IF;
    END IF;

    v_from_status := v_rev.rev_status_id;

    PERFORM set_config('app.action', 'admin_override', true);
    UPDATE core.doc_revision
    SET rev_status_id = p_target_status_id
    WHERE rev_id = p_rev_id;

    INSERT INTO audit.admin_override_audit (
        rev_id, doc_id, from_status_id, to_status_id, reason, changed_by
    ) VALUES (
        p_rev_id, v_rev.doc_id, v_from_status, p_target_status_id, p_reason,
        NULLIF(current_setting('app.user', true), '')::SMALLINT
    );

    IF v_target.final THEN
        PERFORM set_config('app.action', 'transition_final', true);
        UPDATE core.doc_revision
        SET superseded = TRUE
        WHERE doc_id = v_rev.doc_id
          AND rev_id <> p_rev_id
          AND rev_status_id IN (SELECT rev_status_id FROM ref.doc_rev_statuses WHERE final = TRUE)
          AND superseded = FALSE;

        UPDATE core.doc
        SET rev_actual_id = p_rev_id,
            rev_current_id = p_rev_id
        WHERE doc_id = v_rev.doc_id;
    END IF;

    INSERT INTO audit.revision_status_audit (
        rev_id, doc_id, from_status_id, to_status_id, action, reason, changed_by
    ) VALUES (
        p_rev_id, v_rev.doc_id, v_from_status, p_target_status_id, 'admin_override', p_reason,
        NULLIF(current_setting('app.user', true), '')::SMALLINT
    );

    SELECT * INTO v_rev FROM core.doc_revision WHERE rev_id = p_rev_id;
    RETURN v_rev;
END;
$$;

CREATE OR REPLACE FUNCTION workflow.update_document(
    p_doc_id INTEGER,
    p_patch JSONB
) RETURNS core.doc
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = core, ref, workflow, audit, pg_temp
AS $$
DECLARE
    v_doc core.doc%ROWTYPE;
BEGIN
    IF p_patch IS NULL OR p_patch = '{}'::jsonb THEN
        RAISE EXCEPTION 'No fields to update';
    END IF;

    SELECT * INTO v_doc FROM core.doc WHERE doc_id = p_doc_id FOR UPDATE;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'Document not found';
    END IF;

    UPDATE core.doc
    SET doc_name_unique = CASE
            WHEN p_patch ? 'doc_name_unique' THEN p_patch->>'doc_name_unique'
            ELSE doc_name_unique
        END,
        title = CASE
            WHEN p_patch ? 'title' THEN p_patch->>'title'
            ELSE title
        END,
        project_id = CASE
            WHEN p_patch ? 'project_id' THEN (p_patch->>'project_id')::SMALLINT
            ELSE project_id
        END,
        jobpack_id = CASE
            WHEN p_patch ? 'jobpack_id' THEN (p_patch->>'jobpack_id')::SMALLINT
            ELSE jobpack_id
        END,
        type_id = CASE
            WHEN p_patch ? 'type_id' THEN (p_patch->>'type_id')::SMALLINT
            ELSE type_id
        END,
        area_id = CASE
            WHEN p_patch ? 'area_id' THEN (p_patch->>'area_id')::SMALLINT
            ELSE area_id
        END,
        unit_id = CASE
            WHEN p_patch ? 'unit_id' THEN (p_patch->>'unit_id')::SMALLINT
            ELSE unit_id
        END,
        rev_actual_id = CASE
            WHEN p_patch ? 'rev_actual_id' THEN (p_patch->>'rev_actual_id')::INTEGER
            ELSE rev_actual_id
        END,
        rev_current_id = CASE
            WHEN p_patch ? 'rev_current_id' THEN (p_patch->>'rev_current_id')::INTEGER
            ELSE rev_current_id
        END,
        updated_at = NULL,
        updated_by = NULL
    WHERE doc_id = p_doc_id;

    SELECT * INTO v_doc FROM core.doc WHERE doc_id = p_doc_id;
    RETURN v_doc;
END;
$$;

CREATE OR REPLACE FUNCTION workflow.update_revision(
    p_rev_id INTEGER,
    p_patch JSONB
) RETURNS core.doc_revision
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = core, ref, workflow, audit, pg_temp
AS $$
DECLARE
    v_rev core.doc_revision%ROWTYPE;
BEGIN
    IF p_patch IS NULL OR p_patch = '{}'::jsonb THEN
        RAISE EXCEPTION 'No fields to update';
    END IF;

    SELECT * INTO v_rev FROM core.doc_revision WHERE rev_id = p_rev_id FOR UPDATE;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'Revision not found';
    END IF;

    UPDATE core.doc_revision
    SET seq_num = CASE
            WHEN p_patch ? 'seq_num' THEN (p_patch->>'seq_num')::SMALLINT
            ELSE seq_num
        END,
        rev_code_id = CASE
            WHEN p_patch ? 'rev_code_id' THEN (p_patch->>'rev_code_id')::SMALLINT
            ELSE rev_code_id
        END,
        rev_author_id = CASE
            WHEN p_patch ? 'rev_author_id' THEN (p_patch->>'rev_author_id')::SMALLINT
            ELSE rev_author_id
        END,
        rev_originator_id = CASE
            WHEN p_patch ? 'rev_originator_id' THEN (p_patch->>'rev_originator_id')::SMALLINT
            ELSE rev_originator_id
        END,
        rev_modifier_id = CASE
            WHEN p_patch ? 'rev_modifier_id' THEN (p_patch->>'rev_modifier_id')::SMALLINT
            ELSE rev_modifier_id
        END,
        transmital_current_revision = CASE
            WHEN p_patch ? 'transmital_current_revision'
                THEN p_patch->>'transmital_current_revision'
            ELSE transmital_current_revision
        END,
        milestone_id = CASE
            WHEN p_patch ? 'milestone_id' THEN (p_patch->>'milestone_id')::SMALLINT
            ELSE milestone_id
        END,
        planned_start_date = CASE
            WHEN p_patch ? 'planned_start_date' THEN (p_patch->>'planned_start_date')::TIMESTAMPTZ
            ELSE planned_start_date
        END,
        planned_finish_date = CASE
            WHEN p_patch ? 'planned_finish_date' THEN (p_patch->>'planned_finish_date')::TIMESTAMPTZ
            ELSE planned_finish_date
        END,
        actual_start_date = CASE
            WHEN p_patch ? 'actual_start_date' THEN (p_patch->>'actual_start_date')::TIMESTAMPTZ
            ELSE actual_start_date
        END,
        actual_finish_date = CASE
            WHEN p_patch ? 'actual_finish_date' THEN (p_patch->>'actual_finish_date')::TIMESTAMPTZ
            ELSE actual_finish_date
        END,
        as_built = CASE
            WHEN p_patch ? 'as_built' THEN (p_patch->>'as_built')::BOOLEAN
            ELSE as_built
        END,
        modified_doc_date = CASE
            WHEN p_patch ? 'modified_doc_date' THEN (p_patch->>'modified_doc_date')::TIMESTAMPTZ
            ELSE modified_doc_date
        END,
        updated_at = NULL,
        updated_by = NULL
    WHERE rev_id = p_rev_id;

    SELECT * INTO v_rev FROM core.doc_revision WHERE rev_id = p_rev_id;
    RETURN v_rev;
END;
$$;

CREATE OR REPLACE FUNCTION workflow.delete_document(
    p_doc_id INTEGER
) RETURNS TEXT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = core, ref, workflow, audit, pg_temp
AS $$
DECLARE
    v_start_status SMALLINT;
    v_doc core.doc%ROWTYPE;
    v_rev core.doc_revision%ROWTYPE;
    v_count INTEGER;
BEGIN
    SELECT * INTO v_doc FROM core.doc WHERE doc_id = p_doc_id FOR UPDATE;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'Document not found';
    END IF;

    SELECT rev_status_id INTO v_start_status
    FROM ref.doc_rev_statuses WHERE start = TRUE LIMIT 1;
    IF v_start_status IS NULL THEN
        RAISE EXCEPTION 'No start status configured';
    END IF;

    SELECT COUNT(*) INTO v_count FROM core.doc_revision WHERE doc_id = p_doc_id;
    IF v_count = 1 THEN
        SELECT * INTO v_rev FROM core.doc_revision WHERE doc_id = p_doc_id LIMIT 1;
        IF v_rev.rev_status_id = v_start_status THEN
            UPDATE core.doc
            SET rev_current_id = NULL,
                rev_actual_id = NULL
            WHERE doc_id = p_doc_id;
            PERFORM set_config('app.action', 'delete_document', true);
            DELETE FROM core.doc WHERE doc_id = p_doc_id;
            RETURN 'deleted';
        END IF;
    END IF;

    UPDATE core.doc SET voided = TRUE WHERE doc_id = p_doc_id;
    RETURN 'voided';
END;
$$;

CREATE OR REPLACE FUNCTION workflow.create_file(
    p_rev_id INTEGER,
    p_filename VARCHAR,
    p_s3_uid TEXT,
    p_mimetype VARCHAR
) RETURNS core.files
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = core, ref, workflow, audit, pg_temp
AS $$
DECLARE
    v_file core.files%ROWTYPE;
BEGIN
    PERFORM 1 FROM core.doc_revision WHERE rev_id = p_rev_id;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'Revision not found';
    END IF;

    INSERT INTO core.files (
        rev_id, filename, s3_uid, mimetype
    ) VALUES (
        p_rev_id, p_filename, p_s3_uid, p_mimetype
    ) RETURNING * INTO v_file;

    RETURN v_file;
END;
$$;

CREATE OR REPLACE FUNCTION workflow.update_file(
    p_file_id INTEGER,
    p_filename VARCHAR
) RETURNS core.files
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = core, ref, workflow, audit, pg_temp
AS $$
DECLARE
    v_file core.files%ROWTYPE;
BEGIN
    SELECT * INTO v_file FROM core.files WHERE id = p_file_id FOR UPDATE;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'File not found';
    END IF;

    UPDATE core.files
    SET filename = p_filename
    WHERE id = p_file_id;

    SELECT * INTO v_file FROM core.files WHERE id = p_file_id;
    RETURN v_file;
END;
$$;

CREATE OR REPLACE FUNCTION workflow.delete_file(
    p_file_id INTEGER
) RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = core, ref, workflow, audit, pg_temp
AS $$
BEGIN
    PERFORM 1 FROM core.files WHERE id = p_file_id;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'File not found';
    END IF;

    DELETE FROM core.files WHERE id = p_file_id;
END;
$$;

CREATE OR REPLACE FUNCTION workflow.create_file_commented(
    p_file_id INTEGER,
    p_user_id INTEGER,
    p_s3_uid TEXT,
    p_mimetype VARCHAR
) RETURNS core.files_commented
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = core, ref, workflow, audit, pg_temp
AS $$
DECLARE
    v_row core.files_commented%ROWTYPE;
BEGIN
    PERFORM 1 FROM core.files WHERE id = p_file_id;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'File not found';
    END IF;
    PERFORM 1 FROM ref.users WHERE user_id = p_user_id;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'User not found';
    END IF;

    INSERT INTO core.files_commented (
        file_id, user_id, s3_uid, mimetype
    ) VALUES (
        p_file_id, p_user_id, p_s3_uid, p_mimetype
    ) RETURNING * INTO v_row;

    RETURN v_row;
END;
$$;

CREATE OR REPLACE FUNCTION workflow.delete_file_commented(
    p_id INTEGER
) RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = core, ref, workflow, audit, pg_temp
AS $$
BEGIN
    PERFORM 1 FROM core.files_commented WHERE id = p_id;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'Commented file not found';
    END IF;

    DELETE FROM core.files_commented WHERE id = p_id;
END;
$$;

-- --------------------------------------------------------

-- 8. Read-Only Views (schema: workflow)
-- --------------------------------------------------------
CREATE OR REPLACE VIEW workflow.areas AS SELECT * FROM ref.areas;
CREATE OR REPLACE VIEW workflow.disciplines AS SELECT * FROM ref.disciplines;
CREATE OR REPLACE VIEW workflow.projects AS SELECT * FROM ref.projects;
CREATE OR REPLACE VIEW workflow.units AS SELECT * FROM ref.units;
CREATE OR REPLACE VIEW workflow.jobpacks AS SELECT * FROM ref.jobpacks;
CREATE OR REPLACE VIEW workflow.roles AS SELECT * FROM ref.roles;
CREATE OR REPLACE VIEW workflow.doc_rev_milestones AS SELECT * FROM ref.doc_rev_milestones;
CREATE OR REPLACE VIEW workflow.revision_overview AS SELECT * FROM ref.revision_overview;
CREATE OR REPLACE VIEW workflow.doc_rev_statuses AS SELECT * FROM ref.doc_rev_statuses;
CREATE OR REPLACE VIEW workflow.doc_rev_status_ui_behaviors AS SELECT * FROM ref.doc_rev_status_ui_behaviors;
CREATE OR REPLACE VIEW workflow.files_accepted AS SELECT * FROM ref.files_accepted;
CREATE OR REPLACE VIEW workflow.leased_doc_nums AS SELECT * FROM ref.leased_doc_nums;
CREATE OR REPLACE VIEW workflow.sql_queries AS SELECT * FROM ref.sql_queries;
CREATE OR REPLACE VIEW workflow.person AS SELECT * FROM ref.person;
CREATE OR REPLACE VIEW workflow.users AS SELECT * FROM ref.users;
CREATE OR REPLACE VIEW workflow.doc_types AS SELECT * FROM ref.doc_types;
CREATE OR REPLACE VIEW workflow.distribution_list AS SELECT * FROM ref.distribution_list;
CREATE OR REPLACE VIEW workflow.distribution_list_content AS SELECT * FROM ref.distribution_list_content;
CREATE OR REPLACE VIEW workflow.permissions AS SELECT * FROM ref.permissions;
CREATE OR REPLACE VIEW workflow.doc_cache AS SELECT * FROM ref.doc_cache;

CREATE OR REPLACE VIEW workflow.doc AS SELECT * FROM core.doc;
CREATE OR REPLACE VIEW workflow.doc_revision AS SELECT * FROM core.doc_revision;
CREATE OR REPLACE VIEW workflow.files AS SELECT * FROM core.files;
CREATE OR REPLACE VIEW workflow.files_commented AS SELECT * FROM core.files_commented;

CREATE OR REPLACE VIEW workflow.doc_revision_history AS SELECT * FROM audit.doc_revision_history;
CREATE OR REPLACE VIEW workflow.doc_revision_history_view AS
SELECT
    rev_id,
    rev_code_id,
    rev_date,
    rev_author_id,
    rev_originator_id,
    as_built,
    superseded,
    transmital_current_revision,
    milestone_id,
    planned_start_date,
    planned_finish_date,
    actual_start_date,
    actual_finish_date,
    canceled_date,
    rev_status_id,
    doc_id,
    seq_num,
    'HISTORY'::varchar(10) AS source_type
FROM audit.doc_revision_history;

CREATE OR REPLACE VIEW workflow.v_documents AS
SELECT
    d.*, s.rev_status_name AS current_status_name
FROM core.doc d
LEFT JOIN core.doc_revision r ON r.rev_id = d.rev_current_id
LEFT JOIN ref.doc_rev_statuses s ON s.rev_status_id = r.rev_status_id;

CREATE OR REPLACE VIEW workflow.v_document_revisions AS
SELECT
    r.*, s.rev_status_name
FROM core.doc_revision r
JOIN ref.doc_rev_statuses s ON s.rev_status_id = r.rev_status_id;

CREATE OR REPLACE VIEW workflow.v_files AS
SELECT
    f.*, r.doc_id
FROM core.files f
JOIN core.doc_revision r ON r.rev_id = f.rev_id;

-- --------------------------------------------------------

-- 9. Security / Privileges
-- --------------------------------------------------------
REVOKE ALL ON SCHEMA core, ref, audit FROM PUBLIC;
REVOKE ALL ON SCHEMA core, ref, audit FROM app_user;
REVOKE ALL ON ALL TABLES IN SCHEMA core FROM PUBLIC;
REVOKE ALL ON ALL TABLES IN SCHEMA ref FROM PUBLIC;
REVOKE ALL ON ALL TABLES IN SCHEMA audit FROM PUBLIC;

GRANT USAGE ON SCHEMA workflow TO app_user;
REVOKE INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA workflow FROM app_user;
GRANT SELECT ON ALL TABLES IN SCHEMA workflow TO app_user;

GRANT EXECUTE ON FUNCTION workflow.create_document(
    VARCHAR, VARCHAR, SMALLINT, SMALLINT, SMALLINT, SMALLINT, SMALLINT,
    SMALLINT, SMALLINT, SMALLINT, SMALLINT, VARCHAR, SMALLINT,
    TIMESTAMPTZ, TIMESTAMPTZ, TIMESTAMPTZ, TIMESTAMPTZ, TIMESTAMPTZ, BOOLEAN
) TO app_user;

GRANT EXECUTE ON FUNCTION workflow.create_revision(
    INTEGER, SMALLINT, SMALLINT, SMALLINT, SMALLINT, VARCHAR,
    SMALLINT, TIMESTAMPTZ, TIMESTAMPTZ, TIMESTAMPTZ, TIMESTAMPTZ, TIMESTAMPTZ, BOOLEAN
) TO app_user;

GRANT EXECUTE ON FUNCTION workflow.transition_revision(INTEGER, TEXT) TO app_user;
GRANT EXECUTE ON FUNCTION workflow.cancel_revision(INTEGER) TO app_user;
GRANT EXECUTE ON FUNCTION workflow.update_document(INTEGER, JSONB) TO app_user;
GRANT EXECUTE ON FUNCTION workflow.update_revision(INTEGER, JSONB) TO app_user;
GRANT EXECUTE ON FUNCTION workflow.delete_document(INTEGER) TO app_user;
GRANT EXECUTE ON FUNCTION workflow.create_file(INTEGER, VARCHAR, TEXT, VARCHAR) TO app_user;
GRANT EXECUTE ON FUNCTION workflow.update_file(INTEGER, VARCHAR) TO app_user;
GRANT EXECUTE ON FUNCTION workflow.delete_file(INTEGER) TO app_user;
GRANT EXECUTE ON FUNCTION workflow.create_file_commented(INTEGER, INTEGER, TEXT, VARCHAR) TO app_user;
GRANT EXECUTE ON FUNCTION workflow.delete_file_commented(INTEGER) TO app_user;

-- admin override only for db_admin
GRANT EXECUTE ON FUNCTION workflow.admin_override_transition(INTEGER, SMALLINT, TEXT) TO db_admin;

COMMIT;
