-- 2. Reference / Lookup Tables (schema: ref)
-- --------------------------------------------------------
SET search_path = ref;

CREATE TABLE areas (
    area_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    area_name VARCHAR(45) NOT NULL UNIQUE,
    area_acronym VARCHAR(5) NOT NULL UNIQUE
);

CREATE TABLE disciplines (
    discipline_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    discipline_name VARCHAR(45) NOT NULL UNIQUE,
    discipline_acronym VARCHAR(5) NOT NULL UNIQUE
);

CREATE TABLE projects (
    project_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_name VARCHAR(45) NOT NULL UNIQUE
);

CREATE TABLE units (
    unit_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    unit_name VARCHAR(45) NOT NULL UNIQUE
);

CREATE TABLE jobpacks (
    jobpack_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    jobpack_name VARCHAR(45) NOT NULL UNIQUE
);

CREATE TABLE roles (
    role_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name VARCHAR(45) NOT NULL UNIQUE
);

CREATE TABLE doc_rev_milestones (
    milestone_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    milestone_name VARCHAR(45) NOT NULL UNIQUE,
    progress SMALLINT DEFAULT 0
);

CREATE TABLE revision_overview (
    rev_code_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rev_code_name VARCHAR(15) NOT NULL UNIQUE,
    rev_code_acronym VARCHAR(5) NOT NULL,
    rev_description VARCHAR(45) NOT NULL UNIQUE,
    percentage SMALLINT
);

CREATE TABLE doc_rev_status_ui_behaviors (
    ui_behavior_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ui_behavior_name VARCHAR(64) NOT NULL UNIQUE,
    ui_behavior_file VARCHAR(64) NOT NULL UNIQUE
);

CREATE TABLE doc_rev_statuses (
    rev_status_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rev_status_name VARCHAR(45) NOT NULL UNIQUE,
    ui_behavior_id SMALLINT NOT NULL REFERENCES ref.doc_rev_status_ui_behaviors(ui_behavior_id),
    next_rev_status_id SMALLINT REFERENCES ref.doc_rev_statuses(rev_status_id),
    revertible BOOLEAN NOT NULL DEFAULT TRUE,
    editable BOOLEAN NOT NULL DEFAULT TRUE,
    final BOOLEAN NOT NULL DEFAULT FALSE,
    start BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT chk_doc_rev_statuses_no_self_ref CHECK (
        next_rev_status_id IS NULL OR next_rev_status_id <> rev_status_id
    ),
    CONSTRAINT chk_doc_rev_statuses_final_flags CHECK (
        NOT final OR (editable = FALSE AND revertible = FALSE)
    ),
    CONSTRAINT chk_doc_rev_statuses_final_next_eq CHECK (
        final = (next_rev_status_id IS NULL)
    )
);

CREATE UNIQUE INDEX ux_doc_rev_statuses_single_final
    ON ref.doc_rev_statuses ((next_rev_status_id IS NULL))
    WHERE next_rev_status_id IS NULL;

CREATE UNIQUE INDEX ux_doc_rev_statuses_single_start
    ON ref.doc_rev_statuses (start)
    WHERE start = TRUE;

CREATE OR REPLACE FUNCTION ref.doc_rev_statuses_prevent_cycle()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ref, pg_temp
AS $$
DECLARE
    current_id SMALLINT;
BEGIN
    IF NEW.next_rev_status_id IS NULL THEN
        RETURN NEW;
    END IF;

    current_id := NEW.next_rev_status_id;
    WHILE current_id IS NOT NULL LOOP
        IF NEW.rev_status_id IS NOT NULL AND current_id = NEW.rev_status_id THEN
            RAISE EXCEPTION 'Cycle detected in doc_rev_statuses';
        END IF;

        SELECT next_rev_status_id
        INTO current_id
        FROM ref.doc_rev_statuses
        WHERE rev_status_id = current_id;
    END LOOP;

    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_doc_rev_statuses_prevent_cycle
BEFORE INSERT OR UPDATE OF next_rev_status_id
ON ref.doc_rev_statuses
FOR EACH ROW
EXECUTE FUNCTION ref.doc_rev_statuses_prevent_cycle();

CREATE TABLE files_accepted (
    file_type VARCHAR(10) PRIMARY KEY,
    mimetype VARCHAR(90) NOT NULL
);

CREATE TABLE leased_doc_nums (
    doc_number VARCHAR(45) NOT NULL,
    created_date TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE sql_queries (
    id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    query VARCHAR(4096) NOT NULL,
    titles VARCHAR(1024),
    project_filtered_field VARCHAR(45),
    discipline_filtered_field VARCHAR(45)
);

CREATE TABLE person (
    person_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_name VARCHAR(45) NOT NULL,
    photo_s3_uid TEXT,
    email VARCHAR(255)
);

CREATE TABLE users (
    user_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id SMALLINT NOT NULL REFERENCES ref.person(person_id),
    user_acronym VARCHAR(10) NOT NULL,
    role_id SMALLINT NOT NULL REFERENCES ref.roles(role_id),
    UNIQUE (person_id)
);

CREATE TABLE doc_types (
    type_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_type_name VARCHAR(45) NOT NULL,
    ref_discipline_id SMALLINT NOT NULL REFERENCES ref.disciplines(discipline_id),
    doc_type_acronym VARCHAR(10) NOT NULL
);

CREATE TABLE distribution_list (
    dist_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    distribution_list_name VARCHAR(45) NOT NULL,
    project_id SMALLINT NOT NULL REFERENCES ref.projects(project_id)
);

CREATE TABLE distribution_list_content (
    dist_id SMALLINT NOT NULL REFERENCES ref.distribution_list(dist_id),
    person_id SMALLINT NOT NULL REFERENCES ref.person(person_id),
    PRIMARY KEY (dist_id, person_id)
);

CREATE TABLE permissions (
    permission_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id SMALLINT NOT NULL REFERENCES ref.users(user_id),
    project_id SMALLINT REFERENCES ref.projects(project_id),
    discipline_id SMALLINT REFERENCES ref.disciplines(discipline_id),
    CONSTRAINT chk_permissions_scope CHECK (project_id IS NOT NULL OR discipline_id IS NOT NULL)
);

CREATE UNIQUE INDEX uq_permissions_user_proj_disc
    ON ref.permissions(user_id, project_id, discipline_id)
    WHERE project_id IS NOT NULL AND discipline_id IS NOT NULL;

CREATE UNIQUE INDEX uq_permissions_user_proj_anydisc
    ON ref.permissions(user_id, project_id)
    WHERE discipline_id IS NULL;

CREATE UNIQUE INDEX uq_permissions_user_anyproj_disc
    ON ref.permissions(user_id, discipline_id)
    WHERE project_id IS NULL;

CREATE UNIQUE INDEX uq_permissions_user_anyscope
    ON ref.permissions(user_id)
    WHERE project_id IS NULL AND discipline_id IS NULL;

CREATE TABLE doc_cache (
    user_id SMALLINT NOT NULL,
    project_id SMALLINT NOT NULL REFERENCES ref.projects(project_id),
    doc_name_unique VARCHAR(45) NOT NULL UNIQUE,
    title VARCHAR(45) NOT NULL,
    jobpack_id SMALLINT REFERENCES ref.jobpacks(jobpack_id),
    type_id SMALLINT NOT NULL REFERENCES ref.doc_types(type_id),
    area_id SMALLINT NOT NULL REFERENCES ref.areas(area_id),
    unit_id SMALLINT NOT NULL REFERENCES ref.units(unit_id),
    PRIMARY KEY (user_id, project_id, doc_name_unique)
);

-- --------------------------------------------------------
