-- 2. Reference / Lookup Tables (schema: ref)
-- --------------------------------------------------------
SET search_path = ref;

CREATE TABLE areas (
    area_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    area_name VARCHAR(45) NOT NULL UNIQUE,
    area_acronym VARCHAR(5) NOT NULL UNIQUE
);

CREATE TABLE disciplines (
    discipline_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    discipline_name VARCHAR(45) NOT NULL UNIQUE,
    discipline_acronym VARCHAR(5) NOT NULL UNIQUE
);

CREATE TABLE projects (
    project_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_name VARCHAR(45) NOT NULL UNIQUE
);

CREATE TABLE units (
    unit_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    unit_name VARCHAR(45) NOT NULL UNIQUE
);

CREATE TABLE jobpacks (
    jobpack_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    jobpack_name VARCHAR(45) NOT NULL UNIQUE
);

CREATE TABLE roles (
    role_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name VARCHAR(45) NOT NULL UNIQUE,
    role_code VARCHAR(45) UNIQUE,
    external_name VARCHAR(128) UNIQUE,
    is_super BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE doc_rev_milestones (
    milestone_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    milestone_name VARCHAR(45) NOT NULL UNIQUE,
    progress SMALLINT DEFAULT 0
);

CREATE TABLE revision_overview (
    rev_code_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rev_code_name VARCHAR(15) NOT NULL UNIQUE,
    rev_code_acronym VARCHAR(5) NOT NULL,
    rev_description VARCHAR(45) NOT NULL UNIQUE,
    percentage SMALLINT
);

CREATE TABLE doc_rev_status_ui_behaviors (
    ui_behavior_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ui_behavior_name VARCHAR(64) NOT NULL UNIQUE,
    ui_behavior_file VARCHAR(64) NOT NULL UNIQUE
);

CREATE TABLE doc_rev_statuses (
    rev_status_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rev_status_name VARCHAR(45) NOT NULL UNIQUE,
    ui_behavior_id SMALLINT NOT NULL REFERENCES ref.doc_rev_status_ui_behaviors(ui_behavior_id),
    next_rev_status_id SMALLINT REFERENCES ref.doc_rev_statuses(rev_status_id),
    revertible BOOLEAN NOT NULL DEFAULT TRUE,
    editable BOOLEAN NOT NULL DEFAULT TRUE,
    final BOOLEAN NOT NULL DEFAULT FALSE,
    start BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT chk_doc_rev_statuses_no_self_ref CHECK (
        next_rev_status_id IS NULL OR next_rev_status_id <> rev_status_id
    ),
    CONSTRAINT chk_doc_rev_statuses_final_flags CHECK (
        NOT final OR (editable = FALSE AND revertible = FALSE)
    ),
    CONSTRAINT chk_doc_rev_statuses_final_next_eq CHECK (
        final = (next_rev_status_id IS NULL)
    )
);

CREATE UNIQUE INDEX ux_doc_rev_statuses_single_final
    ON ref.doc_rev_statuses ((next_rev_status_id IS NULL))
    WHERE next_rev_status_id IS NULL;

CREATE UNIQUE INDEX ux_doc_rev_statuses_single_start
    ON ref.doc_rev_statuses (start)
    WHERE start = TRUE;

CREATE OR REPLACE FUNCTION ref.doc_rev_statuses_prevent_cycle()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ref, pg_temp
AS $$
DECLARE
    current_id SMALLINT;
BEGIN
    IF NEW.next_rev_status_id IS NULL THEN
        RETURN NEW;
    END IF;

    current_id := NEW.next_rev_status_id;
    WHILE current_id IS NOT NULL LOOP
        IF NEW.rev_status_id IS NOT NULL AND current_id = NEW.rev_status_id THEN
            RAISE EXCEPTION 'Cycle detected in doc_rev_statuses';
        END IF;

        SELECT next_rev_status_id
        INTO current_id
        FROM ref.doc_rev_statuses
        WHERE rev_status_id = current_id;
    END LOOP;

    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_doc_rev_statuses_prevent_cycle
BEFORE INSERT OR UPDATE OF next_rev_status_id
ON ref.doc_rev_statuses
FOR EACH ROW
EXECUTE FUNCTION ref.doc_rev_statuses_prevent_cycle();

CREATE TABLE files_accepted (
    file_type VARCHAR(10) PRIMARY KEY,
    mimetype VARCHAR(90) NOT NULL
);

CREATE TABLE leased_doc_nums (
    doc_number VARCHAR(45) NOT NULL,
    created_date TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE sql_queries (
    id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    query VARCHAR(4096) NOT NULL,
    titles VARCHAR(1024),
    project_filtered_field VARCHAR(45),
    discipline_filtered_field VARCHAR(45)
);

CREATE TABLE instance_parameters (
    parameter VARCHAR(64) PRIMARY KEY,
    value VARCHAR(255) NOT NULL,
    description VARCHAR(1024)
);

CREATE TABLE person_duty (
    duty_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    duty_name VARCHAR(45) NOT NULL UNIQUE
);

CREATE TABLE person (
    person_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_name VARCHAR(45) NOT NULL,
    photo_s3_uid TEXT,
    email VARCHAR(255),
    duty_id SMALLINT REFERENCES ref.person_duty(duty_id)
);

CREATE TABLE users (
    user_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id SMALLINT NOT NULL REFERENCES ref.person(person_id),
    user_acronym VARCHAR(10) NOT NULL,
    role_id SMALLINT NOT NULL REFERENCES ref.roles(role_id),
    UNIQUE (person_id)
);

CREATE TABLE user_roles (
    user_id SMALLINT NOT NULL REFERENCES ref.users(user_id) ON DELETE CASCADE,
    role_id SMALLINT NOT NULL REFERENCES ref.roles(role_id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, role_id)
);

CREATE TABLE role_permissions (
    role_id SMALLINT NOT NULL REFERENCES ref.roles(role_id) ON DELETE CASCADE,
    resource VARCHAR(32) NOT NULL,
    capability VARCHAR(16) NOT NULL,
    CONSTRAINT pk_role_permissions PRIMARY KEY (role_id, resource, capability),
    CONSTRAINT chk_role_permissions_resource CHECK (
        resource IN ('doc', 'doc_revision', 'files', 'files_commented')
    ),
    CONSTRAINT chk_role_permissions_capability CHECK (
        capability IN ('read-only', 'read-write')
    )
);

CREATE TABLE role_scopes (
    role_id SMALLINT NOT NULL REFERENCES ref.roles(role_id) ON DELETE CASCADE,
    scope_type VARCHAR(16) NOT NULL,
    entity_id INTEGER NOT NULL,
    logic_group INTEGER NOT NULL DEFAULT 1,
    CONSTRAINT pk_role_scopes PRIMARY KEY (role_id, scope_type, entity_id, logic_group),
    CONSTRAINT chk_role_scopes_scope_type CHECK (
        scope_type IN ('PROJECT', 'AREA', 'UNIT')
    ),
    CONSTRAINT chk_role_scopes_logic_group_positive CHECK (logic_group > 0)
);

CREATE INDEX ix_roles_role_code ON ref.roles(role_code);
CREATE INDEX ix_roles_external_name ON ref.roles(external_name);
CREATE INDEX ix_user_roles_user_id_role_id ON ref.user_roles(user_id, role_id);
CREATE INDEX ix_role_permissions_role_id_resource_capability
    ON ref.role_permissions(role_id, resource, capability);
CREATE INDEX ix_role_scopes_role_id_scope_entity_group
    ON ref.role_scopes(role_id, scope_type, entity_id, logic_group);

CREATE OR REPLACE FUNCTION ref.sync_user_primary_role()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ref, pg_temp
AS $$
BEGIN
    IF NEW.role_id IS NULL THEN
        RETURN NEW;
    END IF;

    -- Legacy compatibility sync: keep users.role_id mirrored into user_roles,
    -- but do not remove existing secondary role assignments.
    INSERT INTO ref.user_roles (user_id, role_id)
    VALUES (NEW.user_id, NEW.role_id)
    ON CONFLICT (user_id, role_id) DO NOTHING;
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_sync_user_primary_role
AFTER INSERT OR UPDATE OF role_id
ON ref.users
FOR EACH ROW
EXECUTE FUNCTION ref.sync_user_primary_role();

CREATE TABLE doc_types (
    type_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_type_name VARCHAR(45) NOT NULL,
    ref_discipline_id SMALLINT NOT NULL REFERENCES ref.disciplines(discipline_id),
    doc_type_acronym VARCHAR(10) NOT NULL
);

CREATE TABLE permissions (
    permission_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id SMALLINT NOT NULL REFERENCES ref.users(user_id),
    project_id SMALLINT REFERENCES ref.projects(project_id),
    discipline_id SMALLINT REFERENCES ref.disciplines(discipline_id),
    CONSTRAINT chk_permissions_scope CHECK (project_id IS NOT NULL OR discipline_id IS NOT NULL)
);

CREATE UNIQUE INDEX uq_permissions_user_proj_disc
    ON ref.permissions(user_id, project_id, discipline_id)
    WHERE project_id IS NOT NULL AND discipline_id IS NOT NULL;

CREATE UNIQUE INDEX uq_permissions_user_proj_anydisc
    ON ref.permissions(user_id, project_id)
    WHERE discipline_id IS NULL;

CREATE UNIQUE INDEX uq_permissions_user_anyproj_disc
    ON ref.permissions(user_id, discipline_id)
    WHERE project_id IS NULL;

CREATE UNIQUE INDEX uq_permissions_user_anyscope
    ON ref.permissions(user_id)
    WHERE project_id IS NULL AND discipline_id IS NULL;

CREATE TABLE doc_cache (
    user_id SMALLINT NOT NULL,
    project_id SMALLINT NOT NULL REFERENCES ref.projects(project_id),
    doc_name_unique VARCHAR(45) NOT NULL UNIQUE,
    title VARCHAR(45) NOT NULL,
    jobpack_id SMALLINT REFERENCES ref.jobpacks(jobpack_id),
    type_id SMALLINT NOT NULL REFERENCES ref.doc_types(type_id),
    area_id SMALLINT NOT NULL REFERENCES ref.areas(area_id),
    unit_id SMALLINT NOT NULL REFERENCES ref.units(unit_id),
    PRIMARY KEY (user_id, project_id, doc_name_unique)
);

-- --------------------------------------------------------
