-- 3. Core Tables (schema: core)
-- --------------------------------------------------------
SET search_path = core;

CREATE TABLE doc (
    doc_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_name_unique VARCHAR(45) NOT NULL UNIQUE,
    title VARCHAR(45) NOT NULL,
    project_id SMALLINT REFERENCES ref.projects(project_id),
    jobpack_id SMALLINT REFERENCES ref.jobpacks(jobpack_id),
    type_id SMALLINT NOT NULL REFERENCES ref.doc_types(type_id),
    area_id SMALLINT NOT NULL REFERENCES ref.areas(area_id),
    unit_id SMALLINT NOT NULL REFERENCES ref.units(unit_id),
    rev_actual_id INTEGER,
    rev_current_id INTEGER,
    voided BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by SMALLINT REFERENCES ref.users(user_id),
    updated_by SMALLINT REFERENCES ref.users(user_id)
);

CREATE TABLE doc_revision (
    rev_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_id INTEGER NOT NULL REFERENCES core.doc(doc_id) ON DELETE CASCADE,
    rev_code_id SMALLINT NOT NULL REFERENCES ref.revision_overview(rev_code_id),
    seq_num SMALLINT NOT NULL DEFAULT 1,
    rev_status_id SMALLINT NOT NULL REFERENCES ref.doc_rev_statuses(rev_status_id),
    superseded BOOLEAN NOT NULL DEFAULT FALSE,
    transmital_current_revision VARCHAR(45) NOT NULL,
    milestone_id SMALLINT REFERENCES ref.doc_rev_milestones(milestone_id),
    planned_start_date TIMESTAMPTZ NOT NULL,
    planned_finish_date TIMESTAMPTZ NOT NULL,
    actual_start_date TIMESTAMPTZ,
    actual_finish_date TIMESTAMPTZ,
    canceled_date TIMESTAMPTZ,
    rev_author_id SMALLINT NOT NULL REFERENCES ref.person(person_id),
    rev_originator_id SMALLINT NOT NULL REFERENCES ref.person(person_id),
    rev_modifier_id SMALLINT NOT NULL REFERENCES ref.person(person_id),
    modified_doc_date TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    as_built BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by SMALLINT REFERENCES ref.users(user_id),
    updated_by SMALLINT REFERENCES ref.users(user_id)
);

CREATE UNIQUE INDEX ux_doc_revision_rev_doc
    ON core.doc_revision (rev_id, doc_id);

ALTER TABLE core.doc
    ADD CONSTRAINT fk_doc_rev_current
        FOREIGN KEY (rev_current_id, doc_id)
        REFERENCES core.doc_revision (rev_id, doc_id)
        DEFERRABLE INITIALLY DEFERRED,
    ADD CONSTRAINT fk_doc_rev_actual
        FOREIGN KEY (rev_actual_id, doc_id)
        REFERENCES core.doc_revision (rev_id, doc_id)
        DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE files (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rev_id INTEGER NOT NULL REFERENCES core.doc_revision(rev_id) ON DELETE CASCADE,
    filename VARCHAR(90) NOT NULL,
    s3_uid TEXT NOT NULL,
    mimetype VARCHAR(90) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by SMALLINT REFERENCES ref.users(user_id),
    updated_by SMALLINT REFERENCES ref.users(user_id)
);

CREATE TABLE files_commented (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_id INTEGER NOT NULL REFERENCES core.files(id) ON DELETE CASCADE,
    user_id SMALLINT NOT NULL REFERENCES ref.users(user_id),
    s3_uid TEXT NOT NULL,
    mimetype VARCHAR(90) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by SMALLINT REFERENCES ref.users(user_id),
    updated_by SMALLINT REFERENCES ref.users(user_id),
    UNIQUE(file_id, user_id)
);

CREATE INDEX idx_files_commented_file_id ON core.files_commented (file_id);

CREATE TABLE written_comments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rev_id INTEGER NOT NULL REFERENCES core.doc_revision(rev_id) ON DELETE CASCADE,
    user_id SMALLINT NOT NULL REFERENCES ref.users(user_id),
    comment_text TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by SMALLINT REFERENCES ref.users(user_id),
    updated_by SMALLINT REFERENCES ref.users(user_id),
    CONSTRAINT chk_written_comments_not_blank CHECK (btrim(comment_text) <> '')
);

CREATE INDEX idx_written_comments_rev_id ON core.written_comments (rev_id);
CREATE INDEX idx_written_comments_user_id ON core.written_comments (user_id);

CREATE TABLE distribution_list (
    dist_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    distribution_list_name VARCHAR(45) NOT NULL UNIQUE
);

CREATE TABLE distribution_list_content (
    dist_id SMALLINT NOT NULL REFERENCES core.distribution_list(dist_id),
    user_id SMALLINT NOT NULL REFERENCES ref.users(user_id),
    PRIMARY KEY (dist_id, user_id)
);

CREATE INDEX idx_distribution_list_content_user ON core.distribution_list_content(user_id);

CREATE TABLE notifications (
    notification_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender_user_id SMALLINT NOT NULL REFERENCES ref.users(user_id),
    event_type VARCHAR(32) NOT NULL DEFAULT 'regular',
    title VARCHAR(120) NOT NULL,
    body TEXT NOT NULL,
    remark TEXT,
    rev_id INTEGER NOT NULL REFERENCES core.doc_revision(rev_id),
    commented_file_id INTEGER REFERENCES core.files_commented(id),
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    dropped_at TIMESTAMPTZ,
    dropped_by_user_id SMALLINT REFERENCES ref.users(user_id),
    superseded_by_notification_id INTEGER REFERENCES core.notifications(notification_id),
    created_by SMALLINT REFERENCES ref.users(user_id),
    updated_by SMALLINT REFERENCES ref.users(user_id),
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT chk_notifications_event_type CHECK (
        event_type IN ('regular', 'changed_notice', 'dropped_notice')
    ),
    CONSTRAINT chk_notifications_drop_pair CHECK (
        (dropped_at IS NULL AND dropped_by_user_id IS NULL)
        OR (dropped_at IS NOT NULL AND dropped_by_user_id IS NOT NULL)
    ),
    CONSTRAINT chk_notifications_supersede_self CHECK (
        superseded_by_notification_id IS NULL
        OR superseded_by_notification_id <> notification_id
    )
);

CREATE INDEX idx_notifications_sender ON core.notifications(sender_user_id);
CREATE INDEX idx_notifications_rev ON core.notifications(rev_id);
CREATE INDEX idx_notifications_created_at ON core.notifications(created_at DESC);

CREATE TABLE notification_targets (
    target_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notification_id INTEGER NOT NULL REFERENCES core.notifications(notification_id) ON DELETE CASCADE,
    recipient_user_id SMALLINT REFERENCES ref.users(user_id),
    recipient_dist_id SMALLINT REFERENCES core.distribution_list(dist_id),
    CONSTRAINT chk_notification_targets_exactly_one CHECK (
        ((recipient_user_id IS NOT NULL)::INT + (recipient_dist_id IS NOT NULL)::INT) = 1
    )
);

CREATE UNIQUE INDEX ux_notification_targets_user
    ON core.notification_targets(notification_id, recipient_user_id)
    WHERE recipient_user_id IS NOT NULL;

CREATE UNIQUE INDEX ux_notification_targets_dist
    ON core.notification_targets(notification_id, recipient_dist_id)
    WHERE recipient_dist_id IS NOT NULL;

CREATE TABLE notification_recipients (
    notification_id INTEGER NOT NULL REFERENCES core.notifications(notification_id) ON DELETE CASCADE,
    recipient_user_id SMALLINT NOT NULL REFERENCES ref.users(user_id),
    delivered_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    read_at TIMESTAMPTZ,
    PRIMARY KEY (notification_id, recipient_user_id),
    CONSTRAINT chk_notification_recipients_read_after_delivery CHECK (
        read_at IS NULL OR read_at >= delivered_at
    )
);

CREATE INDEX idx_notification_recipients_user_delivery
    ON core.notification_recipients(recipient_user_id, delivered_at DESC);

CREATE OR REPLACE FUNCTION core.fn_notifications_prevent_delete() RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = core, pg_temp
AS $$
BEGIN
    RAISE EXCEPTION 'Notification deletion is forbidden; use replace/delete workflow actions';
END;
$$;

CREATE TRIGGER tr_notifications_prevent_delete
BEFORE DELETE ON core.notifications
FOR EACH ROW EXECUTE FUNCTION core.fn_notifications_prevent_delete();

-- --------------------------------------------------------
