-- 3. Core Tables (schema: core)
-- --------------------------------------------------------
SET search_path = core;

CREATE TABLE doc (
    doc_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_name_unique VARCHAR(45) NOT NULL UNIQUE,
    title VARCHAR(45) NOT NULL,
    project_id SMALLINT REFERENCES ref.projects(project_id),
    jobpack_id SMALLINT REFERENCES ref.jobpacks(jobpack_id),
    type_id SMALLINT NOT NULL REFERENCES ref.doc_types(type_id),
    area_id SMALLINT NOT NULL REFERENCES ref.areas(area_id),
    unit_id SMALLINT NOT NULL REFERENCES ref.units(unit_id),
    rev_actual_id INTEGER,
    rev_current_id INTEGER,
    voided BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by SMALLINT REFERENCES ref.users(user_id),
    updated_by SMALLINT REFERENCES ref.users(user_id)
);

CREATE TABLE doc_revision (
    rev_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_id INTEGER NOT NULL REFERENCES core.doc(doc_id) ON DELETE CASCADE,
    rev_code_id SMALLINT NOT NULL REFERENCES ref.revision_overview(rev_code_id),
    seq_num SMALLINT NOT NULL DEFAULT 1,
    rev_status_id SMALLINT NOT NULL REFERENCES ref.doc_rev_statuses(rev_status_id),
    superseded BOOLEAN NOT NULL DEFAULT FALSE,
    voided BOOLEAN NOT NULL DEFAULT FALSE,
    transmital_current_revision VARCHAR(45) NOT NULL,
    milestone_id SMALLINT REFERENCES ref.doc_rev_milestones(milestone_id),
    planned_start_date TIMESTAMPTZ NOT NULL,
    planned_finish_date TIMESTAMPTZ NOT NULL,
    actual_start_date TIMESTAMPTZ,
    actual_finish_date TIMESTAMPTZ,
    canceled_date TIMESTAMPTZ,
    rev_author_id SMALLINT NOT NULL REFERENCES ref.person(person_id),
    rev_originator_id SMALLINT NOT NULL REFERENCES ref.person(person_id),
    rev_modifier_id SMALLINT NOT NULL REFERENCES ref.person(person_id),
    modified_doc_date TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    as_built BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by SMALLINT REFERENCES ref.users(user_id),
    updated_by SMALLINT REFERENCES ref.users(user_id)
);

CREATE UNIQUE INDEX ux_doc_revision_rev_doc
    ON core.doc_revision (rev_id, doc_id);

ALTER TABLE core.doc
    ADD CONSTRAINT fk_doc_rev_current
        FOREIGN KEY (rev_current_id, doc_id)
        REFERENCES core.doc_revision (rev_id, doc_id)
        DEFERRABLE INITIALLY DEFERRED,
    ADD CONSTRAINT fk_doc_rev_actual
        FOREIGN KEY (rev_actual_id, doc_id)
        REFERENCES core.doc_revision (rev_id, doc_id)
        DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE files (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rev_id INTEGER NOT NULL REFERENCES core.doc_revision(rev_id) ON DELETE CASCADE,
    filename VARCHAR(90) NOT NULL,
    s3_uid TEXT NOT NULL,
    mimetype VARCHAR(90) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by SMALLINT REFERENCES ref.users(user_id),
    updated_by SMALLINT REFERENCES ref.users(user_id)
);

CREATE TABLE files_commented (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_id INTEGER NOT NULL REFERENCES core.files(id) ON DELETE CASCADE,
    user_id SMALLINT NOT NULL REFERENCES ref.users(user_id),
    s3_uid TEXT NOT NULL,
    mimetype VARCHAR(90) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by SMALLINT REFERENCES ref.users(user_id),
    updated_by SMALLINT REFERENCES ref.users(user_id),
    UNIQUE(file_id, user_id)
);

CREATE INDEX idx_files_commented_file_id ON core.files_commented (file_id);

-- --------------------------------------------------------
