-- 4. Audit Tables (schema: audit)
-- --------------------------------------------------------
SET search_path = audit;

CREATE TABLE revision_status_audit (
    audit_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rev_id INTEGER NOT NULL,
    doc_id INTEGER NOT NULL,
    from_status_id SMALLINT,
    to_status_id SMALLINT NOT NULL,
    action VARCHAR(64) NOT NULL,
    reason TEXT,
    changed_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    changed_by SMALLINT
);

CREATE TABLE admin_override_audit (
    audit_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rev_id INTEGER NOT NULL,
    doc_id INTEGER NOT NULL,
    from_status_id SMALLINT,
    to_status_id SMALLINT NOT NULL,
    reason TEXT NOT NULL,
    changed_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    changed_by SMALLINT
);

CREATE TABLE doc_revision_history (
    rev_id INTEGER NOT NULL,
    rev_code_id SMALLINT NOT NULL,
    rev_date TIMESTAMPTZ NOT NULL,
    rev_author_id SMALLINT NOT NULL,
    rev_originator_id SMALLINT NOT NULL,
    as_built BOOLEAN NOT NULL DEFAULT FALSE,
    superseded BOOLEAN NOT NULL DEFAULT FALSE,
    transmital_current_revision VARCHAR(45) NOT NULL,
    milestone_id SMALLINT,
    planned_start_date TIMESTAMPTZ NOT NULL,
    planned_finish_date TIMESTAMPTZ NOT NULL,
    actual_start_date TIMESTAMPTZ,
    actual_finish_date TIMESTAMPTZ,
    canceled_date TIMESTAMPTZ,
    rev_status_id SMALLINT NOT NULL,
    doc_id INTEGER NOT NULL,
    seq_num SMALLINT NOT NULL,
    archived_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (rev_id, archived_at)
);

-- --------------------------------------------------------
