-- 9. Security / Privileges
-- --------------------------------------------------------
REVOKE ALL ON SCHEMA core, ref, audit FROM PUBLIC;
REVOKE ALL ON SCHEMA core, ref, audit FROM app_user;
REVOKE ALL ON ALL TABLES IN SCHEMA core FROM PUBLIC;
REVOKE ALL ON ALL TABLES IN SCHEMA ref FROM PUBLIC;
REVOKE ALL ON ALL TABLES IN SCHEMA audit FROM PUBLIC;

GRANT USAGE ON SCHEMA workflow TO app_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA workflow TO app_user;

GRANT EXECUTE ON FUNCTION workflow.create_document(
    VARCHAR, VARCHAR, SMALLINT, SMALLINT, SMALLINT, SMALLINT, SMALLINT,
    SMALLINT, SMALLINT, SMALLINT, SMALLINT, VARCHAR, SMALLINT,
    TIMESTAMPTZ, TIMESTAMPTZ, TIMESTAMPTZ, TIMESTAMPTZ, TIMESTAMPTZ, BOOLEAN
) TO app_user;

GRANT EXECUTE ON FUNCTION workflow.create_revision(
    INTEGER, SMALLINT, SMALLINT, SMALLINT, SMALLINT, VARCHAR,
    SMALLINT, TIMESTAMPTZ, TIMESTAMPTZ, TIMESTAMPTZ, TIMESTAMPTZ, TIMESTAMPTZ, BOOLEAN
) TO app_user;

GRANT EXECUTE ON FUNCTION workflow.transition_revision(INTEGER, TEXT) TO app_user;
GRANT EXECUTE ON FUNCTION workflow.cancel_revision(INTEGER) TO app_user;

-- admin override only for db_admin
GRANT EXECUTE ON FUNCTION workflow.admin_override_transition(INTEGER, SMALLINT, TEXT) TO db_admin;
