-- ========================================================
-- POSTGRESQL MIGRATION SCRIPT FOR FLOW (FINAL)
-- ========================================================
-- 1. Setup Environment
--    We use a dedicated schema to keep the workspace clean.
-- ========================================================

CREATE SCHEMA IF NOT EXISTS flow;
SET search_path TO flow;

-- ========================================================
-- 2. Reference / Lookup Tables
-- ========================================================

CREATE TABLE areas (
    area_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    area_name VARCHAR(45) NOT NULL UNIQUE,
    area_acronym VARCHAR(5) NOT NULL UNIQUE
);

CREATE TABLE disciplines (
    discipline_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    discipline_name VARCHAR(45) NOT NULL UNIQUE,
    discipline_acronym VARCHAR(5) NOT NULL UNIQUE
);

CREATE TABLE projects (
    project_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_name VARCHAR(45) NOT NULL UNIQUE
);

CREATE TABLE units (
    unit_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    unit_name VARCHAR(45) NOT NULL UNIQUE
);

CREATE TABLE jobpacks (
    jobpack_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    jobpack_name VARCHAR(45) NOT NULL UNIQUE
);

CREATE TABLE roles (
    role_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name VARCHAR(45) NOT NULL UNIQUE
);

CREATE TABLE doc_rev_milestones (
    milestone_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    milestone_name VARCHAR(45) NOT NULL UNIQUE,
    progress SMALLINT DEFAULT 0
);

CREATE TABLE revision_overview (
    rev_code_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rev_code_name VARCHAR(15) NOT NULL UNIQUE,
    rev_code_acronym VARCHAR(5) NOT NULL,
    rev_description VARCHAR(45) NOT NULL UNIQUE,
    percentage SMALLINT
);

CREATE TABLE doc_rev_status_ui_behaviors (
    ui_behavior_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ui_behavior_name VARCHAR(64) NOT NULL UNIQUE
);

CREATE TABLE doc_rev_statuses (
    rev_status_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rev_status_name VARCHAR(45) NOT NULL UNIQUE,
    ui_behavior_id SMALLINT NOT NULL REFERENCES doc_rev_status_ui_behaviors(ui_behavior_id),
    next_rev_status_id SMALLINT REFERENCES doc_rev_statuses(rev_status_id),
    revertible BOOLEAN NOT NULL DEFAULT TRUE,
    editable BOOLEAN NOT NULL DEFAULT TRUE,
    final BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT chk_doc_rev_statuses_no_self_ref CHECK (
        next_rev_status_id IS NULL OR next_rev_status_id <> rev_status_id
    ),
    CONSTRAINT chk_doc_rev_statuses_final_flags CHECK (
        NOT final OR (editable = FALSE AND revertible = FALSE)
    ),
    CONSTRAINT chk_doc_rev_statuses_final_next_eq CHECK (
        final = (next_rev_status_id IS NULL)
    )
);

CREATE UNIQUE INDEX ux_doc_rev_statuses_single_final
    ON doc_rev_statuses ((next_rev_status_id IS NULL))
    WHERE next_rev_status_id IS NULL;

CREATE OR REPLACE FUNCTION doc_rev_statuses_prevent_cycle()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    current_id SMALLINT;
BEGIN
    IF NEW.next_rev_status_id IS NULL THEN
        RETURN NEW;
    END IF;

    current_id := NEW.next_rev_status_id;
    WHILE current_id IS NOT NULL LOOP
        IF NEW.rev_status_id IS NOT NULL AND current_id = NEW.rev_status_id THEN
            RAISE EXCEPTION 'Cycle detected in doc_rev_statuses';
        END IF;

        SELECT next_rev_status_id
        INTO current_id
        FROM flow.doc_rev_statuses
        WHERE rev_status_id = current_id;
    END LOOP;

    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_doc_rev_statuses_prevent_cycle
BEFORE INSERT OR UPDATE OF next_rev_status_id
ON doc_rev_statuses
FOR EACH ROW
EXECUTE FUNCTION doc_rev_statuses_prevent_cycle();

CREATE TABLE files_accepted (
    file_type VARCHAR(10) PRIMARY KEY,
    mimetype VARCHAR(90) NOT NULL
);

CREATE TABLE leased_doc_nums (
    doc_number VARCHAR(45) NOT NULL,
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);



-- ========================================================
-- 3. Relation & User Tables
-- ========================================================

CREATE TABLE person (
    person_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_name VARCHAR(45) NOT NULL,
    photo_s3_uid TEXT
);

CREATE TABLE users (
    user_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id SMALLINT NOT NULL REFERENCES person(person_id),
    user_acronym VARCHAR(10) NOT NULL,
    role_id SMALLINT NOT NULL REFERENCES roles(role_id),
    UNIQUE (person_id)
);

CREATE TABLE doc_types (
    type_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_type_name VARCHAR(45) NOT NULL,
    ref_discipline_id SMALLINT NOT NULL REFERENCES disciplines(discipline_id),
    doc_type_acronym VARCHAR(10) NOT NULL
);

CREATE TABLE distribution_list (
    dist_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    distribution_list_name VARCHAR(45) NOT NULL,
    project_id SMALLINT NOT NULL REFERENCES projects(project_id)
);

CREATE TABLE distribution_list_content (
    dist_id SMALLINT NOT NULL REFERENCES distribution_list(dist_id),
    person_id SMALLINT NOT NULL REFERENCES person(person_id),
    PRIMARY KEY (dist_id, person_id)
);

CREATE TABLE permissions (
    permission_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id SMALLINT NOT NULL REFERENCES users(user_id),
    project_id SMALLINT REFERENCES projects(project_id),
    discipline_id SMALLINT REFERENCES disciplines(discipline_id),
    CONSTRAINT chk_permissions_scope CHECK (project_id IS NOT NULL OR discipline_id IS NOT NULL)
);

CREATE UNIQUE INDEX uq_permissions_user_proj_disc
    ON permissions(user_id, project_id, discipline_id)
    WHERE project_id IS NOT NULL AND discipline_id IS NOT NULL;

CREATE UNIQUE INDEX uq_permissions_user_proj_anydisc
    ON permissions(user_id, project_id)
    WHERE discipline_id IS NULL;

CREATE UNIQUE INDEX uq_permissions_user_anyproj_disc
    ON permissions(user_id, discipline_id)
    WHERE project_id IS NULL;

CREATE UNIQUE INDEX uq_permissions_user_anyscope
    ON permissions(user_id)
    WHERE project_id IS NULL AND discipline_id IS NULL;

-- ========================================================
-- 4. Core Documentation Tables
-- ========================================================

CREATE TABLE doc (
    doc_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_name_unique VARCHAR(45) NOT NULL UNIQUE,
    title VARCHAR(45) NOT NULL,
    project_id SMALLINT REFERENCES projects(project_id),
    jobpack_id SMALLINT REFERENCES jobpacks(jobpack_id),
    type_id SMALLINT NOT NULL REFERENCES doc_types(type_id),
    area_id SMALLINT NOT NULL REFERENCES areas(area_id),
    unit_id SMALLINT NOT NULL REFERENCES units(unit_id),
    rev_actual_id INTEGER,
    rev_current_id INTEGER
);

CREATE TABLE doc_cache (
    user_id SMALLINT NOT NULL,
    project_id SMALLINT NOT NULL REFERENCES projects(project_id),
    doc_name_unique VARCHAR(45) NOT NULL UNIQUE,
    title VARCHAR(45) NOT NULL,
    jobpack_id SMALLINT REFERENCES jobpacks(jobpack_id),
    type_id SMALLINT NOT NULL REFERENCES doc_types(type_id),
    area_id SMALLINT NOT NULL REFERENCES areas(area_id),
    unit_id SMALLINT NOT NULL REFERENCES units(unit_id),
    PRIMARY KEY (user_id, project_id, doc_name_unique)
);

CREATE TABLE doc_revision (
    rev_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rev_code_id SMALLINT NOT NULL REFERENCES revision_overview(rev_code_id),
    rev_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    rev_author_id SMALLINT NOT NULL REFERENCES person(person_id),
    rev_originator_id SMALLINT NOT NULL REFERENCES person(person_id),
    as_built VARCHAR(3),
    superseded VARCHAR(3),
    voided VARCHAR(3),
    transmital_current_revision VARCHAR(45) NOT NULL,
    milestone_id SMALLINT REFERENCES doc_rev_milestones(milestone_id),
    planned_start_date TIMESTAMP NOT NULL,
    planned_finish_date TIMESTAMP NOT NULL,
    actual_start_date TIMESTAMP,
    actual_finish_date TIMESTAMP,
    canceled_date VARCHAR(45),
    rev_status_id SMALLINT NOT NULL REFERENCES doc_rev_statuses(rev_status_id),
    doc_id INTEGER NOT NULL REFERENCES doc(doc_id) ON DELETE CASCADE,
    seq_num SMALLINT NOT NULL DEFAULT 1,
    rev_modifier_id SMALLINT,
    modified_doc_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

ALTER TABLE doc 
    ADD CONSTRAINT fk_doc_rev_current FOREIGN KEY (rev_current_id) REFERENCES doc_revision(rev_id),
    ADD CONSTRAINT fk_doc_rev_actual FOREIGN KEY (rev_actual_id) REFERENCES doc_revision(rev_id);

CREATE TABLE doc_revision_history (
    rev_id INTEGER NOT NULL,
    rev_code_id SMALLINT NOT NULL,
    rev_date TIMESTAMP NOT NULL,
    rev_author_id SMALLINT NOT NULL,
    rev_originator_id SMALLINT NOT NULL,
    as_built VARCHAR(3),
    superseded VARCHAR(3),
    voided VARCHAR(3),
    transmital_current_revision VARCHAR(45) NOT NULL,
    milestone_id SMALLINT,
    planned_start_date TIMESTAMP NOT NULL,
    planned_finish_date TIMESTAMP NOT NULL,
    actual_start_date TIMESTAMP,
    actual_finish_date TIMESTAMP,
    canceled_date VARCHAR(45),
    rev_status_id SMALLINT NOT NULL,
    doc_id INTEGER NOT NULL,
    seq_num SMALLINT NOT NULL,
    archived_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE files (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    filename VARCHAR(90) NOT NULL,
    s3_uid TEXT NOT NULL,
    mimetype VARCHAR(90) NOT NULL,
    rev_id INTEGER NOT NULL REFERENCES doc_revision(rev_id) ON DELETE CASCADE
);

CREATE TABLE files_commented (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_id INTEGER NOT NULL REFERENCES files(id) ON DELETE CASCADE,
    user_id SMALLINT NOT NULL REFERENCES users(user_id),
    s3_uid TEXT NOT NULL,
    mimetype VARCHAR(90) NOT NULL,
    UNIQUE(file_id, user_id)
);

CREATE INDEX idx_files_commented_file_id ON files_commented (file_id);

-- ========================================================
-- 5. Views
-- ========================================================

CREATE OR REPLACE VIEW doc_revision_history_view AS
    SELECT 
        rev_id, rev_code_id, rev_date, rev_author_id, rev_originator_id,
        as_built, superseded, voided, 
        transmital_current_revision, 
        milestone_id,
        planned_start_date, planned_finish_date, actual_start_date, actual_finish_date,
        canceled_date, rev_status_id, doc_id, seq_num, 
        'CURRENT' as source_type
    FROM doc_revision 
    UNION ALL 
    SELECT 
        rev_id, rev_code_id, rev_date, rev_author_id, rev_originator_id,
        as_built, superseded, voided, 
        transmital_current_revision, 
        milestone_id,
        planned_start_date, planned_finish_date, actual_start_date, actual_finish_date,
        canceled_date, rev_status_id, doc_id, seq_num,
        'HISTORY' as source_type
    FROM doc_revision_history;

-- ========================================================
-- 6. Business Logic (Triggers)
-- ========================================================

CREATE OR REPLACE FUNCTION fn_doc_revision_after_insert() RETURNS TRIGGER AS $$
BEGIN
    UPDATE doc SET rev_current_id = NEW.rev_id WHERE doc_id = NEW.doc_id;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER tr_doc_revision_after_insert
AFTER INSERT ON doc_revision
FOR EACH ROW EXECUTE FUNCTION fn_doc_revision_after_insert();

CREATE OR REPLACE FUNCTION fn_doc_revision_after_update() RETURNS TRIGGER AS $$
BEGIN
    IF NEW.rev_code_id <> OLD.rev_code_id THEN
        INSERT INTO doc_revision_history (
            rev_id, rev_code_id, rev_date, rev_author_id, rev_originator_id, 
            as_built, superseded, voided, 
            transmital_current_revision, 
            milestone_id, 
            planned_start_date, planned_finish_date, actual_start_date, actual_finish_date, 
            canceled_date, rev_status_id, doc_id, seq_num
        ) VALUES (
            OLD.rev_id, OLD.rev_code_id, OLD.rev_date, OLD.rev_author_id, OLD.rev_originator_id, 
            OLD.as_built, OLD.superseded, OLD.voided, 
            OLD.transmital_current_revision, 
            OLD.milestone_id, 
            OLD.planned_start_date, OLD.planned_finish_date, OLD.actual_start_date, 
            NOW(),
            OLD.canceled_date, OLD.rev_status_id, OLD.doc_id, OLD.seq_num
        );
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER tr_doc_revision_after_update
AFTER UPDATE ON doc_revision
FOR EACH ROW EXECUTE FUNCTION fn_doc_revision_after_update();

CREATE OR REPLACE FUNCTION fn_doc_revision_before_delete() RETURNS TRIGGER AS $$
BEGIN
    DELETE FROM files_commented WHERE file_id IN (SELECT id FROM files WHERE rev_id = OLD.rev_id);
    DELETE FROM files WHERE rev_id = OLD.rev_id;
    RETURN OLD;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER tr_doc_revision_before_delete
BEFORE DELETE ON doc_revision
FOR EACH ROW EXECUTE FUNCTION fn_doc_revision_before_delete();

CREATE OR REPLACE FUNCTION fn_doc_revision_after_delete() RETURNS TRIGGER AS $$
BEGIN
    UPDATE doc SET rev_current_id = rev_actual_id WHERE doc_id = OLD.doc_id;
    RETURN OLD;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER tr_doc_revision_after_delete
AFTER DELETE ON doc_revision
FOR EACH ROW EXECUTE FUNCTION fn_doc_revision_after_delete();

CREATE OR REPLACE FUNCTION fn_files_commented_check_mimetype() RETURNS TRIGGER AS $$
DECLARE
    original_mimetype VARCHAR(90);
BEGIN
    SELECT mimetype INTO original_mimetype FROM flow.files WHERE id = NEW.file_id;
    IF original_mimetype IS NULL THEN
        RAISE EXCEPTION 'File not found for commented file_id=%', NEW.file_id
            USING ERRCODE = '23503';
    END IF;
    IF NEW.mimetype IS NULL OR lower(NEW.mimetype) <> lower(original_mimetype) THEN
        RAISE EXCEPTION 'Commented file mimetype % does not match original %',
            NEW.mimetype, original_mimetype
            USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER tr_files_commented_check_mimetype
BEFORE INSERT OR UPDATE ON files_commented
FOR EACH ROW EXECUTE FUNCTION fn_files_commented_check_mimetype();
